### ISSUE TITLE
Touchables positioned absolutely outside KeyboardAccessoryView do not respond

### ISSUE THREAD

**Issue by Thorbenandresen** [wix/react-native-keyboard-input#12]
Hi @artald ,

I want to make a keyboard-tracking "scroll to bottom" slideout like in WhatsApp (iOS).

I positioned the red slideout absolutely and it displays/ animates correctly. However the part of the slideout which is visually above the KeyboardAccessoryView (green box) does not respond to touches (it actually passes touches right through to the chat list view). The part of the touchable which is inside the KeyboardAccessoryView works fine. 

![simulator_screen_shot_apr_19__2017__4_50_36_pm](https://cloud.githubusercontent.com/assets/8238976/25202018/c12f6034-2521-11e7-8d3f-2472fdb51c40.png)

**Comment by artald** [comment]
Hey @Thorbenandresen 

That's really weird.. do you also have teachability issues with other views inside your scroll? 

How hard would it be for you to create a reproducible gist for the demo project?
I suspect that this issue might be subjected to certain layouts and styles, so it would greatly help if I can easily reproduce it. thanks!

**Comment by Thorbenandresen** [comment]
@artald I made a gist here: https://gist.github.com/Thorbenandresen/acf035c57b930b7b7c53aec7467f21c5

This is so far the only touchability issue I ran into.

**Comment by artald** [comment]
Great, thanks. I'll look into it

**Comment by artald** [comment]
@Thorbenandresen it seems that there's no simple solution for this issue.

The problem results from the way the react-native is handling touches on the native side, more specifically how it "hit tests" views to check which view was touched.
The `TouchableOpacity` view is a child of the `KeyboardAccessoryView`, but it is positioned outside of it, outside of its frame; that's what's causing the problem.

This issue is not related specifically to this package. You will get the same behavior for touchable views that are placed outside of the frame of their parent component.

For example, try to put the following code in your render function. You'll see that touches don't work either:
```
<View style={{width: 375, height: 200, backgroundColor: 'blue'}}>
      <View style={{position: 'absolute', top: 270, right: 0}}>
        <TouchableOpacity
          onPress={() => console.error('pressed!')}
          style={{height: 30, width: 40, backgroundColor: 'red'}}
        >
          <Text>Press me</Text>
        </TouchableOpacity>
      </View>
    </View>
```

One possible solution could be to add the button to the ScrollView itself and keep the button "floating" in a fixed position. It's possible to do it by listening to scroll events and adjust the position according to the `contentOffset`. To avoid performance issues I strongly recommend to use `Animated.ScrollView` for this task.

**Comment by Thorbenandresen** [comment]
@artald thank you for looking into it. I'll check out your suggestions
