### ISSUE TITLE
Issues/Questions about keyboard dismiss

### ISSUE THREAD

**Issue by Thorbenandresen** [wix/react-native-keyboard-input#2]
Hi,

thanks a lot for making this available to everyone!

I have couple of issues / questions about dismissing the custom keyboards:

* on iOS with `keyboardDismissMode: interactive`, the KeyboardAccessoryView's renderContent (i.e. the input bar) will stay fixed, while only the custom keyboard components are dismissed interactively. This is not a problem when the native keyboard is shown.

![simulator screen shot mar 29 2017 8 54 22 pm](https://cloud.githubusercontent.com/assets/8238976/24483265/dab10ebc-14c4-11e7-9f48-041ca5bf9c32.png)

* on Android `keyboardDismissMode: on-drag` does only work when the native keyboard is shown, but not when a custom keyboard is shown.

* is there a method to dismiss a custom keyboard ? (e.g. which I can attach to an onClick handler outside the keyboard). Keyboard.dismiss() does only dismiss when the native keyboard is shown, but not when a custom keyboard is shown.

RN 0.38 / demoApp.js

**Comment by artald** [comment]
Hi Thorban,

Thanks for reporting about these issues. This package is still a WIP and there might still be a couple of quirks here and there.

We're already working on improving the interactive drag behavior, mainly on iOS at the moment but hopefully soon on Android too.

We'll also look into the keyboard dismissing issue you've mentioned when we can.. if you really need this, a possible "hacky" solution could be to first reset the keyboard (switch to system keyboard) and then dismiss (haven't tried this though)

**Comment by artald** [comment]
@Thorbenandresen version 3.0.0 that was recently published includes improved keyboard tracking for the interactive mode. On Android, by the way, keyboard dismiss modes are not supported by the system (also mentioned in the react native docs) so that's why it doesn't work.

Would love to hear if this works for you.

**Comment by Thorbenandresen** [comment]
@artald thank you! I have only tried the demoApp, but it works great there!

As for keyboardDismissMode on Android. I think 'on-drag' works on Andorid and the note in the docs refers to the 'interactive' mode.

**Comment by artald** [comment]
@Thorbenandresen Regarding the keyboard dismiss, I added a utility method that you can now use:
```
import {KeyboardUtils} from 'react-native-keyboard-input';
KeyboardUtils.dismiss()
```

Regarding the 'on-drag' mode on android - I think you're right. It's confusing because in the docs it is mentioned at the end in a separate sentence :)
I asked some Android developers and they said that it's not really a common pattern on Android, so I think this is not urgent. Please feel free to open a separate issue if you really need it.

**Comment by Thorbenandresen** [comment]
@artald thanks so much! You are right, I also asked around and Android keyboard dismiss seems to be either handled by the back button or the tapping the underlying view.
