### ISSUE TITLE
Use KeyboardAvoidingView ?

### ISSUE THREAD

**Issue by alexisbronchart** [wix/react-native-keyboard-input#37]
Is there a specific reason why there is a dependency on react-native-keyboard-tracking-view? Why not use KeyboardAvoidingView?

**Comment by artald** [comment]
`react-native-keyboard-tracking-view` has many advantages, among them:
- tracks the keyboard accurately as it moves, also when performing interactive drag.
- manages a containing scroll-view insets automatically - essential if you're working with keyboards.
- handles safe area correctly (I assume that the avoiding view has some issues with that since its a JS based solution with no respect or reference to safe area insets).

together with the tracking-view, this package delivers a complete solution for handling an accessory view and handling of custom keyboards. There was a debate if the packages should merge but we decided that the tracking-view has a value on its own.

**Comment by milesscherrer** [comment]
There is now a UIWebView deprecation that goes into effect April 2020 affecting react-native-keyboard-tracking-view which will block new apps from being accepted to the app store.
